### ISSUE TITLE
ypeError: Failed to convert object of type <type 'list'> to Tensor. Contents: [8, None, 0, 16, 8]. Consider casting elements to a supported type.

### ISSUE THREAD

**Issue by qaazii** [Zengyi-Qin/MonoGRNet#16]
i am having this error. i dont know how to resolve can someone help?

**Comment by Zengyi-Qin** [comment]
Could you please tell us where the error comes? Which file and which line?

**Comment by qazi876** [comment]
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 78, in main
    train.do_training(hypes)
  File "/home/lps/MonoGRNet/tensorvision/train.py", line 377, in do_training
    tv_graph, labels = core.build_training_graph(hypes, queue, modules)
  File "/home/lps/MonoGRNet/tensorvision/core.py", line 85, in build_training_graph
    logits = encoder.inference(hypes, image, train=True)
  File "/home/lps/MonoGRNet/hypes/../encoder/vgg.py", line 35, in inference
    random_init_fc8=True)
  File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 98, in build
    self.conv4_depth, self.conv4_location, self.conv4_corner = self._image_encoder(self.conv4_3, 128, (6, 12, 18), 'conv4_encoder')
  File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 124, in _image_encoder
    full = self._conv_layer_new(full_neck, name + '_full', 3, 1, (256, 128), 'depth')
  File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 168, in _conv_layer_new
    conv = self._group_norm(conv) if use_norm else conv
  File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 206, in _group_norm
    x = tf.reshape(x, [N, H, W, G, C // G])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
TypeError: Failed to convert object of type <type 'list'> to Tensor. Contents: [8, None, 0, 16, 8]. Consider casting elements to a supported type.

**Comment by qaazii** [comment]
> Could you please tell us where the error comes? Which file and which line?
Traceback (most recent call last):
File "train.py", line 82, in
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "train.py", line 78, in main
train.do_training(hypes)
File "/home/lps/MonoGRNet/tensorvision/train.py", line 377, in do_training
tv_graph, labels = core.build_training_graph(hypes, queue, modules)
File "/home/lps/MonoGRNet/tensorvision/core.py", line 85, in build_training_graph
logits = encoder.inference(hypes, image, train=True)
File "/home/lps/MonoGRNet/hypes/../encoder/vgg.py", line 35, in inference
random_init_fc8=True)
File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 98, in build
self.conv4_depth, self.conv4_location, self.conv4_corner = self._image_encoder(self.conv4_3, 128, (6, 12, 18), 'conv4_encoder')
File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 124, in _image_encoder
full = self._conv_layer_new(full_neck, name + '_full', 3, 1, (256, 128), 'depth')
File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 168, in _conv_layer_new
conv = self._group_norm(conv) if use_norm else conv
File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 206, in _group_norm
x = tf.reshape(x, [N, H, W, G, C // G])
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3938, in reshape
"Reshape", tensor=tensor, shape=shape, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
raise err
TypeError: Failed to convert object of type <type 'list'> to Tensor. Contents: [8, None, 0, 16, 8]. Consider casting elements to a supported type.

**Comment by qaazii** [comment]
> Could you please tell us where the error comes? Which file and which line?

Thanks for your reply. I posted the error above the file is fcn8_vgg.py and line 206. Could you please check the error? 

I tried in many ways but still the same error. Seems like in the following code H value is None and W value is 0 and i also think there is some problem with input feeding. The problem is i don't fully understand. can you help to find what is the problem.
File "/home/lps/MonoGRNet/include/tensorflow_fcn/fcn8_vgg.py", line 206, in _group_norm
x = tf.reshape(x, [N, H, W, G, C // G])

**Comment by Zengyi-Qin** [comment]
Possibly the error is due to an incompatible version of tensorflow. Have you tried setting up a clean virtual environment with Python2.7 & Tensorflow 1.4? Maybe it will make a difference.

**Comment by qazi876** [comment]
> Possibly the error is due to an incompatible version of tensorflow. Have you tried setting up a clean virtual environment with Python2.7 & Tensorflow 1.4? Maybe it will make a difference.

I cleared the environment. the error is because regression_weights  was not defined in 

File "/home/lps/MonoGRNet/hypes/../decoder/fastBox.py", line 741, in loss
regression_weights = hypes['solver']['regression_weights']

I cleared it and the code is training now properly but i have problem in evaluation. 

File "/home/lps/MonoGRNet/tensorvision/train.py", line 289, in run_training
    hypes, sess, tv_graph['image_pl'], tv_graph['inf_out'])
TypeError: evaluate() takes exactly 6 arguments (4 given)

line 289 is eval_dict, images = modules['eval'].evaluate(
                hypes, sess, tv_graph['image_pl'],  tv_graph['inf_out'])
4 inputs is given but evaluate in file eval.py is line 59 is "def evaluate(hypes, sess, image_pl, calib_pl, xy_scale_pl, softmax):" 6 inputs are given. 

now when i changed the inputs still gives error. could you please have a look to find out what inputs i need to give in order to evaluate. 


Thanks in advance.

**Comment by qaazii** [comment]
I solved it. It was because there was two folders of tensorvision.Thank you for your support. could you please tell how the evaluation is done. it takes too much time and shows some images of 2d detection. how to get 3d object detected images. Thanks in advance.
